// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoulmateStore.Data;

#nullable disable

namespace SoulmateStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314125135_AddWishlistPromotionCouponBoxReviewStock")]
    partial class AddWishlistPromotionCouponBoxReviewStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoulmateStore.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Apartment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("District")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("BoxTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BoxTypeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "OrderId", "BoxTypeId")
                        .IsUnique();

                    b.ToTable("BoxReviews");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("BoxTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterGender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlotKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoxTypeId");

                    b.HasIndex("SlotKey");

                    b.ToTable("BoxSlots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000001"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "ساعة",
                            LabelEn = "Watch",
                            SlotKey = "watch",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000002"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "محفظة",
                            LabelEn = "Wallet",
                            SlotKey = "wallet",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000003"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "مج",
                            LabelEn = "Mug",
                            SlotKey = "mug",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000004"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "سلسلة",
                            LabelEn = "Necklace",
                            SlotKey = "necklace",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000005"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "خاتم",
                            LabelEn = "Ring",
                            SlotKey = "ring",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000001"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "ساعة",
                            LabelEn = "Watch",
                            SlotKey = "watch",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000002"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "محفظة",
                            LabelEn = "Wallet",
                            SlotKey = "wallet",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000003"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "مج",
                            LabelEn = "Mug",
                            SlotKey = "mug",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000004"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "عقد",
                            LabelEn = "Necklace",
                            SlotKey = "necklace",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000005"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "خاتم",
                            LabelEn = "Ring",
                            SlotKey = "ring",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000001"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "ساعة له",
                            LabelEn = "Watch for Him",
                            SlotKey = "watch",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000002"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "ساعة لها",
                            LabelEn = "Watch for Her",
                            SlotKey = "watch",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000003"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            IsRequired = true,
                            LabelAr = "محفظة",
                            LabelEn = "Wallet",
                            SlotKey = "wallet",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000004"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "مج له",
                            LabelEn = "Mug for Him",
                            SlotKey = "mug",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000005"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "مج لها",
                            LabelEn = "Mug for Her",
                            SlotKey = "mug",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000006"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "عقد",
                            LabelEn = "Necklace",
                            SlotKey = "necklace",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000007"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            IsRequired = true,
                            LabelAr = "خاتم",
                            LabelEn = "Ring",
                            SlotKey = "ring",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BoxTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BasePrice = 200m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "male",
                            ImageUrl = "/assets/images/box-male.webp",
                            IsActive = true,
                            Name = "البوكس الرجالي",
                            NameEn = "Men's Box",
                            Slug = "male-box",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            BasePrice = 200m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "female",
                            ImageUrl = "/assets/images/box-female.webp",
                            IsActive = true,
                            Name = "البوكس الحريمي",
                            NameEn = "Women's Box",
                            Slug = "female-box",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            BasePrice = 350m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "couple",
                            ImageUrl = "/assets/images/box-couple.webp",
                            IsActive = true,
                            Name = "بوكس لأجلكما",
                            NameEn = "Couple's Box",
                            Slug = "couple-box",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SoulmateStore.Models.CategoryCustomizationPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.ToTable("CategoryCustomizationPrices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc000000-0000-0000-0000-000000000001"),
                            Category = "watch",
                            Price = 50m
                        },
                        new
                        {
                            Id = new Guid("cc000000-0000-0000-0000-000000000002"),
                            Category = "wallet",
                            Price = 40m
                        },
                        new
                        {
                            Id = new Guid("cc000000-0000-0000-0000-000000000003"),
                            Category = "mug",
                            Price = 30m
                        },
                        new
                        {
                            Id = new Guid("cc000000-0000-0000-0000-000000000004"),
                            Category = "necklace",
                            Price = 45m
                        },
                        new
                        {
                            Id = new Guid("cc000000-0000-0000-0000-000000000005"),
                            Category = "ring",
                            Price = 35m
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("IsActive");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("SoulmateStore.Models.Governorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "القاهرة",
                            NameEn = "Cairo",
                            ShippingCost = 50m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "الجيزة",
                            NameEn = "Giza",
                            ShippingCost = 50m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "الإسكندرية",
                            NameEn = "Alexandria",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            IsActive = true,
                            Name = "الدقهلية",
                            NameEn = "Dakahlia",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            IsActive = true,
                            Name = "البحيرة",
                            NameEn = "Beheira",
                            ShippingCost = 65m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            IsActive = true,
                            Name = "المنيا",
                            NameEn = "Minya",
                            ShippingCost = 70m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            IsActive = true,
                            Name = "القليوبية",
                            NameEn = "Qalyubia",
                            ShippingCost = 50m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            IsActive = true,
                            Name = "الشرقية",
                            NameEn = "Sharqia",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            IsActive = true,
                            Name = "الغربية",
                            NameEn = "Gharbia",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            IsActive = true,
                            Name = "المنوفية",
                            NameEn = "Monufia",
                            ShippingCost = 55m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            IsActive = true,
                            Name = "كفر الشيخ",
                            NameEn = "Kafr El Sheikh",
                            ShippingCost = 65m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000c"),
                            IsActive = true,
                            Name = "الفيوم",
                            NameEn = "Fayoum",
                            ShippingCost = 65m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000d"),
                            IsActive = true,
                            Name = "بني سويف",
                            NameEn = "Beni Suef",
                            ShippingCost = 65m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000e"),
                            IsActive = true,
                            Name = "أسيوط",
                            NameEn = "Assiut",
                            ShippingCost = 75m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000000f"),
                            IsActive = true,
                            Name = "سوهاج",
                            NameEn = "Sohag",
                            ShippingCost = 75m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            IsActive = true,
                            Name = "قنا",
                            NameEn = "Qena",
                            ShippingCost = 80m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            IsActive = true,
                            Name = "الأقصر",
                            NameEn = "Luxor",
                            ShippingCost = 80m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            IsActive = true,
                            Name = "أسوان",
                            NameEn = "Aswan",
                            ShippingCost = 85m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            IsActive = true,
                            Name = "دمياط",
                            NameEn = "Damietta",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000014"),
                            IsActive = true,
                            Name = "بورسعيد",
                            NameEn = "Port Said",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000015"),
                            IsActive = true,
                            Name = "الإسماعيلية",
                            NameEn = "Ismailia",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000016"),
                            IsActive = true,
                            Name = "السويس",
                            NameEn = "Suez",
                            ShippingCost = 60m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000017"),
                            IsActive = true,
                            Name = "شمال سيناء",
                            NameEn = "North Sinai",
                            ShippingCost = 80m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000018"),
                            IsActive = true,
                            Name = "جنوب سيناء",
                            NameEn = "South Sinai",
                            ShippingCost = 85m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000019"),
                            IsActive = true,
                            Name = "مطروح",
                            NameEn = "Matrouh",
                            ShippingCost = 80m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000001a"),
                            IsActive = true,
                            Name = "الوادي الجديد",
                            NameEn = "New Valley",
                            ShippingCost = 90m
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-00000000001b"),
                            IsActive = true,
                            Name = "البحر الأحمر",
                            NameEn = "Red Sea",
                            ShippingCost = 85m
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SoulmateStore.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SoulmateStore.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("BoxTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BoxTypeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SoulmateStore.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScreenshotUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SoulmateStore.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBuilderItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomizable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStandalone")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Gender");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsBuilderItem");

                    b.HasIndex("IsCustomizable");

                    b.HasIndex("IsStandalone");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("StockQuantity");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000001"),
                            Category = "watch",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ساعة رجالي ذهبية بتصميم كلاسيكي أنيق",
                            DescriptionEn = "Elegant men's gold watch with a classic design",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/watch/men-classic-gold-watch.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "ساعة ذهبية كلاسيك رجالي",
                            NameEn = "Classic Gold Men's Watch",
                            Price = 450m,
                            Slug = "men-classic-gold-watch",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000002"),
                            Category = "watch",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ساعة رجالي بإطار أسود من الستانلس ستيل",
                            DescriptionEn = "Men's watch with a black stainless steel frame",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/watch/men-black-steel-watch.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "ساعة سوداء ستيل رجالي",
                            NameEn = "Black Steel Men's Watch",
                            Price = 400m,
                            Slug = "men-black-steel-watch",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000003"),
                            Category = "watch",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ساعة رجالي رياضية فضية اللون",
                            DescriptionEn = "Silver-toned sporty men's watch",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/watch/men-silver-sport-watch.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = false,
                            IsStandalone = true,
                            Name = "ساعة فضية رياضية رجالي",
                            NameEn = "Silver Sport Men's Watch",
                            Price = 380m,
                            Slug = "men-silver-sport-watch",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000004"),
                            Category = "watch",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ساعة نسائي بلون روز جولد راقي",
                            DescriptionEn = "Refined women's watch in rose gold",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/watch/women-rose-gold-watch.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "ساعة روز جولد نسائي",
                            NameEn = "Rose Gold Women's Watch",
                            Price = 420m,
                            Slug = "women-rose-gold-watch",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000005"),
                            Category = "watch",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ساعة نسائي بتصميم بسيط وأنيق",
                            DescriptionEn = "Women's watch with a sleek minimal design",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/watch/women-minimal-watch.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "ساعة مينيمال نسائي",
                            NameEn = "Minimal Women's Watch",
                            Price = 350m,
                            Slug = "women-minimal-watch",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000006"),
                            Category = "watch",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ساعة نسائي بسوار لؤلؤي فاخر",
                            DescriptionEn = "Luxurious women's watch with a pearl bracelet",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/watch/women-pearl-watch.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "ساعة لؤلؤية نسائي",
                            NameEn = "Pearl Women's Watch",
                            Price = 480m,
                            Slug = "women-pearl-watch",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000001"),
                            Category = "wallet",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "محفظة رجالي من الجلد الطبيعي البني",
                            DescriptionEn = "Men's wallet made of genuine brown leather",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/wallet/men-brown-leather-wallet.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "محفظة جلد بني رجالي",
                            NameEn = "Brown Leather Men's Wallet",
                            Price = 280m,
                            Slug = "men-brown-leather-wallet",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000002"),
                            Category = "wallet",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "محفظة رجالي رفيعة بلون أسود أنيق",
                            DescriptionEn = "Slim men's wallet in elegant black",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/wallet/men-black-slim-wallet.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "محفظة سليم سوداء رجالي",
                            NameEn = "Black Slim Men's Wallet",
                            Price = 250m,
                            Slug = "men-black-slim-wallet",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000003"),
                            Category = "wallet",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "محفظة رجالي كلاسيكية بجيوب متعددة",
                            DescriptionEn = "Classic men's wallet with multiple compartments",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/wallet/men-classic-wallet.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = false,
                            IsStandalone = true,
                            Name = "محفظة كلاسيك رجالي",
                            NameEn = "Classic Men's Wallet",
                            Price = 300m,
                            Slug = "men-classic-wallet",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000004"),
                            Category = "wallet",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "محفظة نسائي بلون وردي جذاب",
                            DescriptionEn = "Women's wallet in an attractive pink color",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/wallet/women-pink-wallet.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "محفظة وردية نسائي",
                            NameEn = "Pink Women's Wallet",
                            Price = 260m,
                            Slug = "women-pink-wallet",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000005"),
                            Category = "wallet",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "محفظة نسائي بلون بيج كلاسيكي",
                            DescriptionEn = "Women's wallet in classic beige",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/wallet/women-beige-wallet.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "محفظة بيج نسائي",
                            NameEn = "Beige Women's Wallet",
                            Price = 270m,
                            Slug = "women-beige-wallet",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000006"),
                            Category = "wallet",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "محفظة نسائي بلمسة ذهبية أنيقة",
                            DescriptionEn = "Women's wallet with an elegant gold accent",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/wallet/women-gold-wallet.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "محفظة ذهبية نسائي",
                            NameEn = "Gold Women's Wallet",
                            Price = 290m,
                            Slug = "women-gold-wallet",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-0003-0003-0003-000000000001"),
                            Category = "mug",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مج أسود بتصميم رجالي مميز",
                            DescriptionEn = "Black mug with a distinctive men's design",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/mug/men-black-mug.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "مج أسود رجالي",
                            NameEn = "Black Men's Mug",
                            Price = 120m,
                            Slug = "men-black-mug",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-0003-0003-0003-000000000002"),
                            Category = "mug",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مج رمادي بلمسة عصرية",
                            DescriptionEn = "Grey mug with a modern touch",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/mug/men-grey-mug.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "مج رمادي رجالي",
                            NameEn = "Grey Men's Mug",
                            Price = 120m,
                            Slug = "men-grey-mug",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-0003-0003-0003-000000000003"),
                            Category = "mug",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مج بلون كحلي أنيق",
                            DescriptionEn = "Elegant navy-colored mug",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/mug/men-navy-mug.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "مج كحلي رجالي",
                            NameEn = "Navy Men's Mug",
                            Price = 130m,
                            Slug = "men-navy-mug",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-0003-0003-0003-000000000004"),
                            Category = "mug",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مج وردي بتصميم ناعم",
                            DescriptionEn = "Pink mug with a soft design",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/mug/women-pink-mug.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "مج وردي نسائي",
                            NameEn = "Pink Women's Mug",
                            Price = 120m,
                            Slug = "women-pink-mug",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-0003-0003-0003-000000000005"),
                            Category = "mug",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مج بتصميم مرمري فاخر",
                            DescriptionEn = "Mug with a luxurious marble design",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/mug/women-marble-mug.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "مج مرمري نسائي",
                            NameEn = "Marble Women's Mug",
                            Price = 140m,
                            Slug = "women-marble-mug",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-0003-0003-0003-000000000006"),
                            Category = "mug",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "مج بنقشة زهور رقيقة",
                            DescriptionEn = "Mug with a delicate floral pattern",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/mug/women-floral-mug.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = false,
                            IsStandalone = true,
                            Name = "مج فلورال نسائي",
                            NameEn = "Floral Women's Mug",
                            Price = 130m,
                            Slug = "women-floral-mug",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-0004-0004-0004-000000000001"),
                            Category = "necklace",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "سلسلة رجالي من الفضة الخالصة",
                            DescriptionEn = "Men's chain made of pure silver",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/necklace/men-silver-chain.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "سلسلة فضية رجالي",
                            NameEn = "Silver Men's Chain",
                            Price = 220m,
                            Slug = "men-silver-chain",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-0004-0004-0004-000000000002"),
                            Category = "necklace",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "سلسلة رجالي من الستانلس ستيل",
                            DescriptionEn = "Men's stainless steel chain",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/necklace/men-steel-chain.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = false,
                            IsStandalone = true,
                            Name = "سلسلة ستيل رجالي",
                            NameEn = "Steel Men's Chain",
                            Price = 180m,
                            Slug = "men-steel-chain",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-0004-0004-0004-000000000003"),
                            Category = "necklace",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "سلسلة رجالي بتصميم بسيط",
                            DescriptionEn = "Men's chain with a minimal design",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/necklace/men-minimal-chain.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "سلسلة مينيمال رجالي",
                            NameEn = "Minimal Men's Chain",
                            Price = 200m,
                            Slug = "men-minimal-chain",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-0004-0004-0004-000000000004"),
                            Category = "necklace",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "عقد نسائي بتعليقة قلب رقيقة",
                            DescriptionEn = "Women's necklace with a dainty heart pendant",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/necklace/women-heart-necklace.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "عقد قلب نسائي",
                            NameEn = "Heart Women's Necklace",
                            Price = 250m,
                            Slug = "women-heart-necklace",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-0004-0004-0004-000000000005"),
                            Category = "necklace",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "عقد نسائي بلؤلؤ طبيعي",
                            DescriptionEn = "Women's necklace with natural pearls",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/necklace/women-pearl-necklace.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "عقد لؤلؤ نسائي",
                            NameEn = "Pearl Women's Necklace",
                            Price = 320m,
                            Slug = "women-pearl-necklace",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-0004-0004-0004-000000000006"),
                            Category = "necklace",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "عقد نسائي بتعليقة ذهبية أنيقة",
                            DescriptionEn = "Women's necklace with an elegant gold pendant",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/necklace/women-gold-pendant.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "عقد ذهبي نسائي",
                            NameEn = "Gold Women's Pendant",
                            Price = 280m,
                            Slug = "women-gold-pendant",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-0005-0005-0005-000000000001"),
                            Category = "ring",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خاتم رجالي من التيتانيوم المتين",
                            DescriptionEn = "Durable men's titanium ring",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/ring/men-titanium-ring.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "خاتم تيتانيوم رجالي",
                            NameEn = "Titanium Men's Ring",
                            Price = 200m,
                            Slug = "men-titanium-ring",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-0005-0005-0005-000000000002"),
                            Category = "ring",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خاتم رجالي فضي بتصميم كلاسيكي",
                            DescriptionEn = "Classic silver men's ring",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/ring/men-silver-ring.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = false,
                            IsStandalone = true,
                            Name = "خاتم فضي رجالي",
                            NameEn = "Silver Men's Ring",
                            Price = 180m,
                            Slug = "men-silver-ring",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-0005-0005-0005-000000000003"),
                            Category = "ring",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خاتم رجالي أسود أنيق",
                            DescriptionEn = "Elegant black men's ring",
                            Gender = "male",
                            ImageUrl = "/assets/mock-products/ring/men-black-ring.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "خاتم أسود رجالي",
                            NameEn = "Black Men's Ring",
                            Price = 190m,
                            Slug = "men-black-ring",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-0005-0005-0005-000000000004"),
                            Category = "ring",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خاتم نسائي مرصع بالألماس",
                            DescriptionEn = "Women's ring studded with diamonds",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/ring/women-diamond-ring.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "خاتم ألماس نسائي",
                            NameEn = "Diamond Women's Ring",
                            Price = 350m,
                            Slug = "women-diamond-ring",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-0005-0005-0005-000000000005"),
                            Category = "ring",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خاتم نسائي ذهبي رقيق",
                            DescriptionEn = "Delicate gold women's ring",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/ring/women-gold-ring.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = true,
                            IsStandalone = true,
                            Name = "خاتم ذهبي نسائي",
                            NameEn = "Gold Women's Ring",
                            Price = 280m,
                            Slug = "women-gold-ring",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-0005-0005-0005-000000000006"),
                            Category = "ring",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "خاتم نسائي فضي بتصميم مميز",
                            DescriptionEn = "Silver women's ring with a unique design",
                            Gender = "female",
                            ImageUrl = "/assets/mock-products/ring/women-silver-ring.webp",
                            IsActive = true,
                            IsBuilderItem = true,
                            IsCustomizable = false,
                            IsStandalone = true,
                            Name = "خاتم فضي نسائي",
                            NameEn = "Silver Women's Ring",
                            Price = 220m,
                            Slug = "women-silver-ring",
                            StockQuantity = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("EndDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductId");

                    b.HasIndex("StartDate");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("SoulmateStore.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SoulmateStore.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SoulmateStore.Models.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SoulmateStore.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredLang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("customer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@soulmate-store.com",
                            FailedLoginAttempts = 0,
                            Name = "Admin",
                            PasswordHash = "$2a$11$9Z5R6K39Y4AWgmB6aFyvh.CjYm6EEESBzyuBTGQrguHhFa48c642S",
                            Phone = "01000000000",
                            PreferredLang = "ar",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("SoulmateStore.Models.Address", b =>
                {
                    b.HasOne("SoulmateStore.Models.Governorate", "Governorate")
                        .WithMany()
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxReview", b =>
                {
                    b.HasOne("SoulmateStore.Models.BoxType", "BoxType")
                        .WithMany()
                        .HasForeignKey("BoxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoxType");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxSlot", b =>
                {
                    b.HasOne("SoulmateStore.Models.BoxType", "BoxType")
                        .WithMany("BoxSlots")
                        .HasForeignKey("BoxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoxType");
                });

            modelBuilder.Entity("SoulmateStore.Models.Cart", b =>
                {
                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("SoulmateStore.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.Notification", b =>
                {
                    b.HasOne("SoulmateStore.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.Order", b =>
                {
                    b.HasOne("SoulmateStore.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.OrderItem", b =>
                {
                    b.HasOne("SoulmateStore.Models.BoxType", "BoxType")
                        .WithMany()
                        .HasForeignKey("BoxTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulmateStore.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BoxType");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoulmateStore.Models.Payment", b =>
                {
                    b.HasOne("SoulmateStore.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoulmateStore.Models.Promotion", b =>
                {
                    b.HasOne("SoulmateStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoulmateStore.Models.RefreshToken", b =>
                {
                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.Review", b =>
                {
                    b.HasOne("SoulmateStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.Wishlist", b =>
                {
                    b.HasOne("SoulmateStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxType", b =>
                {
                    b.Navigation("BoxSlots");
                });

            modelBuilder.Entity("SoulmateStore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SoulmateStore.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
