// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoulmateStore.Data;

#nullable disable

namespace SoulmateStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306081439_UpdateBoxTypeImages")]
    partial class UpdateBoxTypeImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoulmateStore.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Apartment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("BoxTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterGender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SlotKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoxTypeId");

                    b.HasIndex("SlotKey");

                    b.ToTable("BoxSlots");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000001"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "ساعة",
                            SlotKey = "watch",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000002"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "محفظة",
                            SlotKey = "wallet",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000003"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "مج",
                            SlotKey = "mug",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000004"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "سلسلة",
                            SlotKey = "chain",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000005"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "كبك",
                            SlotKey = "cufflinks",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("11111111-0001-0001-0001-000000000006"),
                            BoxTypeId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "خاتم",
                            SlotKey = "ring",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000001"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "ساعة",
                            SlotKey = "watch",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000002"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "محفظة",
                            SlotKey = "wallet",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000003"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "مج",
                            SlotKey = "mug",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000004"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "عقد",
                            SlotKey = "necklace",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000005"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "إسورة",
                            SlotKey = "bracelet",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-0002-0002-0002-000000000006"),
                            BoxTypeId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "حلق",
                            SlotKey = "earrings",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000001"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "ساعة له",
                            SlotKey = "watch",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000002"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "ساعة لها",
                            SlotKey = "watch",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000003"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            IsRequired = true,
                            LabelAr = "محفظة",
                            SlotKey = "wallet",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000004"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "male",
                            IsRequired = true,
                            LabelAr = "مج له",
                            SlotKey = "mug",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000005"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "مج لها",
                            SlotKey = "mug",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000006"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            FilterGender = "female",
                            IsRequired = true,
                            LabelAr = "عقد",
                            SlotKey = "necklace",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("33333333-0003-0003-0003-000000000007"),
                            BoxTypeId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            IsRequired = true,
                            LabelAr = "خاتم",
                            SlotKey = "ring",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BoxTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BasePrice = 200m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "male",
                            ImageUrl = "/assets/images/box-male.webp",
                            IsActive = true,
                            Name = "البوكس الرجالي",
                            Slug = "male-box",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            BasePrice = 200m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "female",
                            ImageUrl = "/assets/images/box-female.webp",
                            IsActive = true,
                            Name = "البوكس الحريمي",
                            Slug = "female-box",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            BasePrice = 350m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Gender = "couple",
                            ImageUrl = "/assets/images/box-couple.webp",
                            IsActive = true,
                            Name = "بوكس لأجلكما",
                            Slug = "couple-box",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SoulmateStore.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SoulmateStore.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("BoxTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BoxTypeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SoulmateStore.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScreenshotUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SoulmateStore.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GalleryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsStandalone")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Gender");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsStandalone");

                    b.HasIndex("SlotType");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SoulmateStore.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SoulmateStore.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("customer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@soulmate-store.com",
                            FailedLoginAttempts = 0,
                            Name = "Admin",
                            PasswordHash = "$2a$11$ZYFKOP4eBiJBangTJim4m.o90GXRsWCmGJbCMbXEUbC5RbGOOVBdS",
                            Phone = "01000000000",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("SoulmateStore.Models.Address", b =>
                {
                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxSlot", b =>
                {
                    b.HasOne("SoulmateStore.Models.BoxType", "BoxType")
                        .WithMany("BoxSlots")
                        .HasForeignKey("BoxTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoxType");
                });

            modelBuilder.Entity("SoulmateStore.Models.Notification", b =>
                {
                    b.HasOne("SoulmateStore.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.Order", b =>
                {
                    b.HasOne("SoulmateStore.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.OrderItem", b =>
                {
                    b.HasOne("SoulmateStore.Models.BoxType", "BoxType")
                        .WithMany()
                        .HasForeignKey("BoxTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoulmateStore.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoulmateStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BoxType");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoulmateStore.Models.Payment", b =>
                {
                    b.HasOne("SoulmateStore.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SoulmateStore.Models.RefreshToken", b =>
                {
                    b.HasOne("SoulmateStore.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SoulmateStore.Models.BoxType", b =>
                {
                    b.Navigation("BoxSlots");
                });

            modelBuilder.Entity("SoulmateStore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SoulmateStore.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
