// Injects the API base URL into src/environments/environment.ts at build time.
// Set API_BASE_URL in the build environment (e.g. a Vercel env var).
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const rawApiUrl = process.env.API_BASE_URL?.trim();

if (!rawApiUrl) {
  console.error('[set-env] API_BASE_URL is required for production builds. Set it to https://soulmate.runasp.net.');
  process.exit(1);
}

let apiUrl;
try {
  const parsed = new URL(rawApiUrl);
  if (!['http:', 'https:'].includes(parsed.protocol)) {
    throw new Error('URL must use http or https.');
  }
  if (/^(localhost|127\.0\.0\.1)$/i.test(parsed.hostname)) {
    throw new Error('Production API_BASE_URL must not point to localhost.');
  }
  const normalizedPath = parsed.pathname.replace(/\/+$/, '');
  if (normalizedPath && normalizedPath !== '/api') {
    throw new Error('API_BASE_URL must not include a path other than /api.');
  }
  apiUrl = parsed.origin;
} catch (error) {
  console.error(`[set-env] API_BASE_URL is invalid: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
}

const target = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'environments', 'environment.ts');

writeFileSync(
  target,
  `// Generated by scripts/set-env.mjs - do not commit changes to this file.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`,
);

console.log(`[set-env] environment.ts written with apiUrl=${apiUrl}`);
