// Injects the API base URL into src/environments/environment.ts at build time.
// Set API_BASE_URL in the build environment (e.g. a Vercel env var).
// When unset, the committed file (safe localhost default) is left untouched.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const apiUrl = process.env.API_BASE_URL;

if (!apiUrl) {
  console.log('[set-env] API_BASE_URL not set - keeping committed environment.ts');
  process.exit(0);
}

if (!/^https?:\/\/[^'\\]+$/.test(apiUrl)) {
  console.error(`[set-env] API_BASE_URL is not a valid http(s) URL: ${apiUrl}`);
  process.exit(1);
}

const target = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'environments', 'environment.ts');

writeFileSync(
  target,
  `// Generated by scripts/set-env.mjs - do not commit changes to this file.
export const environment = {
  production: true,
  apiUrl: '${apiUrl.replace(/\/+$/, '')}',
};
`,
);

console.log(`[set-env] environment.ts written with apiUrl=${apiUrl}`);
